### ISSUE TITLE
C# 新版sdk 没有 根据文件前缀获取 文件列表的方法

### ISSUE THREAD

**Issue by peaceful321** [qiniu/csharp-sdk#102]
目前新版的 C# SDK 只能通过 list 接口获取 空间文件的列表，
sdk没有提供该方法来实现该功能，
应该是还没写，建议补充一下。

**Comment by fengyhack** [comment]
谢谢反馈。"获取空间文件的列表"这个功能将会被会加到SDK中。

**Comment by fengyhack** [comment]
已补充: BucketManager.listFiles(...)
