### ISSUE TITLE
有没有WinCE 6.0的解决方案

### ISSUE THREAD

**Issue by smartepsh** [qiniu/csharp-sdk#103]
因为Json.net最新版本不太兼容wince 6.0, (实际上差不多兼容的要到3.5r8版本了)

所以SDK在Mac mac = new mac(ak,sk)的时候就报错了, 源码大概看了下,应该就是因为几个override的toString地方出的错.

暂时打算自己重写相关的JSON函数. 因为没有通读代码,所以想先问一下,SDK本身是否支持WINCE设备? 

CE6仅有.net cf 2和.net cf 3.5.

时间不是很多,怕是只能做一些json的更改了,害怕到时候SDK本身也有什么问题.

**Comment by fengyhack** [comment]
这个SDK在内部用到的是HttpWebRequest/HttpWebResponse，所以也比较好兼容，换言之，主要问题还是JSON这一块。

Json.NET用在两个地方：

1.对象转换为jsonString（也就是你说的toString，修改起来很简单）

2.从jsonString解析对象 （JsonConvert.DeserializeObject，修改起来较为复杂）

或者可能的话，尝试一下使用兼容CE6的Json.NET。

**Comment by smartepsh** [comment]
只有理论上支持ce6的json.net......我试过换了一个网上所谓的3.5r8的版本(现在是9.0,年代久远),提示变了,大意就是有些方法找不到了...我再试一下吧.

如果只用了HttpWeb的话,那应该没有问题的,我会试着写一下...解析对象我倒是能做(都是泪,JSON.NET的兼容问题, 自己手写过...我们服务器用的JSONAPI,解析起来比一般JSON还恶心...)

我用你们的工具传个图片,截一下数据包看看....大概看要解析个几层的....
