### ISSUE TITLE
有没有人跟我同样的感觉，6.0的以下版本更.NET呢？

### ISSUE THREAD

**Issue by cipchk** [qiniu/csharp-sdk#108]
从7.0开始就非常难用，特别是 `uploadFile` 竟然只提供一种回调的方式，好累呀。也许是我智商问题。总感觉写.NET SDK的人，是NODEJS过来的。

有没有人有同感？

最后我还是回到了6.x了。

**Comment by fengyhack** [comment]
感谢@cipchk 的反馈，这些反馈对于SDK得改进都有帮助。
事实上7.0是"另一个版本"，而不是"平滑升级的版本"，所以6->7有些突兀。
对于惯用风格，类似于`ret = func(params...)`这种，在7.0版本中改用`func(params...,delegate)`，这种风格可能会让人不适应。
另外，还有一个改写的.NET Core版本，看上去更符合惯用的风格，您可以参阅一番。
后面考虑将7.0版本重构。

**Comment by cipchk** [comment]
@fengyhack 采用回调的风格并不是太合理，当然我也很清楚出于性能之类的考虑。

但是否可以采用 `async` 呢？

**Comment by fengyhack** [comment]
后续改用HttpClient方式，可以考虑async
