### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by kimmoda** [qiniu/csharp-sdk#112]
Hello , when ı qiniu login with github ı get this error : [7336] 第三方账号认证失败

**Comment by lilanjun2016** [comment]
hi, do you go to this page,https://portal.qiniu.com/user/vendor,you should  do it first, after this you communicate with us .

**Comment by lilanjun2016** [comment]
hi, do you go to this page,https://portal.qiniu.com/user/vendor,you should  do it first, after this you communicate with us .

**Comment by kimmoda** [comment]
This page 404 error 您正在访问另一个平行宇宙中的页面，七牛正在灰常努力的解决通信问题，或许您可以先尝试返回首页

**Comment by fengyhack** [comment]
You may try [this link](https://portal.qiniu.com/user/vendor)

**Comment by kimmoda** [comment]
ı living in turkey , and ı cant register with phone number.

**Comment by lilanjun2016** [comment]
I suggest you can register with email.   from this page  
[https://portal.qiniu.com/signup?type=1](https://portal.qiniu.com/signup?type=1)

**Comment by kimmoda** [comment]
![screen](https://cloud.githubusercontent.com/assets/24658354/21386534/ec1de0f8-c77b-11e6-8eb9-0f3772529bc2.PNG)


this page request phone number.

**Comment by lilanjun2016** [comment]
hi
you see this picture.
[https://oi6684sny.qnssl.com/222.png](https://oi6684sny.qnssl.com/222.png)
whether you can not receive the messages when you input you phone numbers and click the button "kodunu al..".
we are very sorry about your troubles.

**Comment by kimmoda** [comment]
For Turkey , not working ?

**Comment by kimmoda** [comment]
or you can register for me ? really need a account for keys.

**Comment by lilanjun2016** [comment]
sorry. I hear of that the foreign number can not receive the messages.

**Comment by lilanjun2016** [comment]
Just you as you say, Turkey is not working.
Sorry.

**Comment by kimmoda** [comment]
ı can login with github ?

**Comment by lilanjun2016** [comment]
hi 
that is  register with  email first and then relate with gitHub. So it can not register with github.Sorry.

**Comment by kimmoda** [comment]
what is your country phone code ?

**Comment by lilanjun2016** [comment]
I am in China and I am a chinese. Why do you need my phone number ?  I am a employee in Qiniu.You can get the number of our company:  400-808-9176

**Comment by kimmoda** [comment]
ı dont ask your phone number , ı ask just china phone code , thanks anyway . ı try this number but not working +85264522656

**Comment by kimmoda** [comment]
13862277693 for this number ı get this error  [-1] 未知错误，请创建工单获取帮助

**Comment by lilanjun2016** [comment]
oh, sorry 
+86  this is the china phone code.
you get the error   [-1] 未知错误，请创建工单获取帮助 。can you give us the screenshot  about this error. thank you .
