### ISSUE TITLE
存在内存泄漏问题，上传过大的文件会崩溃！！

### ISSUE THREAD

**Issue by inethink** [qiniu/csharp-sdk#113]
上传文件过程中，内存无法释放，一直增长。上传1.5G左右的文件，内存也会一直上涨到1.5G，造成崩溃！！

**Comment by fengyhack** [comment]
@inethink 

给的信息不是很全（可以在支持或者工单中给一下上传token或者抓包信息），所以只能给一些参考。

上传大文件使用的是分片上传（直接支持断点续上传），需要注意一些一些地方：

1.上传策略(PutPolicy)设置里面有一项是过期时间expire，根据实际情况来设置。如果待上传的文件很大，上传耗时较长，而**设置的expire太短可能会导致上传失败**；

2.上一次更新版本7.0.0.5使用HttpWebRequest/HttpWebResponse，根据实际情况可能会消耗更多内存，完成具体请求后会及时关闭(SDK代码中主动关闭)，后续由GC自动回收内存，也因此可能会堆积到一定大小；

3.如果有上传大文件需求，推荐使用[QSunSync工具](https://github.com/qiniu/QSunSync)

**Comment by inethink** [comment]
@fengyhack 
谢谢您的回复。
1、还原这个问题，您只需要使用QSUNSYNC工具上传一个大文件，在任务管理器中，该软件的内存会不断增大（以分片阈值的大小增大），直至崩溃！！
2、对此问题已经提交过工单，但回复风牛马不及。所以才到这里找您！

任务管理器的一段时间的情况：
名称	PID	状态	用户名	CPU	内存(专用工作集)	描述
QSunSync.exe	1740	正在运行	iNethink	01 	212,628 K	QSunSync
QSunSync.exe	1740	正在运行	iNethink	00 	228,636 K	QSunSync
QSunSync.exe	1740	正在运行	iNethink	01 	249,296 K	QSunSync
QSunSync.exe	1740	正在运行	iNethink	01 	1149,296 K	QSunSync

**Comment by fengyhack** [comment]
@inethink 
感谢您的反馈。
从您的描述来看，专用内存一直在上涨，但没有主动回收。
我们这边检查一下SDK和工具的源代码，尽快找到问题并优化。

**Comment by inethink** [comment]
@fengyhack 
谢谢您。是SDK的问题。工具本身没有问题。感谢！

**Comment by fengyhack** [comment]
@inethink 

可以参考[v7.1.0.0版本](https://github.com/fengyhack/csharp-sdk-shared)，内存占用不再出现之前的"暴涨"问题。

此版本SDK文档请参阅 [在线版本](http://oiy037d6a.bkt.clouddn.com/csharp-sdk-help/index.html) 或者[离线chm文件](http://oiy037d6a.bkt.clouddn.com/Qiniu-CSharp-SDK-Ref.chm)

如有问题或建议，欢迎反馈。非常感谢。
