### ISSUE TITLE
MVC项目通过Nuget引用报错未能加载文件或程序集“Qiniu”或它的某一个依赖项

### ISSUE THREAD

**Issue by Tinkerc** [qiniu/csharp-sdk#114]
新建空web mvc项目，通过nuget引用qiniu，运行就报错

未能加载文件或程序集“Qiniu”或它的某一个依赖项。试图加载格式不正确的程序。

**Comment by fengyhack** [comment]
@Tinkerc 

感谢您的反馈。

1.是否.NET Core项目？如果是，请引用.NET Core版本的dll（暂时没有推送到NuGet，近期会推送上去），如果不是，请参考2

2.是否引用到Newtonsoft.Json？如果是，请添加引用或者卸载后重新安装该引用

**Comment by itlizhi** [comment]
我升级到7.0.0.1后，也出现了类似问题。

提示：C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3270: 所生成项目的处理器架构“MSIL”与引用“Qiniu, Version=1.0.0.0, Culture=neutral, processorArchitecture=x86”的处理器架构“x86”不匹配。这种不匹配可能会导致运行时失败。请考虑通过配置管理器更改您的项目的目标处理器架构，以使您的项目与引用间的处理器架构保持一致，或者为引用关联一个与您的项目的目标处理器架构相符的处理器架构。

猜测是因为计算机的版本是x64，但是这个版本编译的是x86的。

**Comment by fengyhack** [comment]
@itlizhi 
感谢您的反馈。
从报错提示来看，是编译目标不一样，SDK(Qiniu.dll)是x86而项目是x64的。

以下是一些可能的办法，请**选择其中一个**来尝试：

1.使用最新版本的SDK，编译为AnyCPU适用于x86和x64
2.或者使用重写的C# SDK，戳[这里](https://github.com/fengyhack/csharp-sdk-shared)
3.修改项目配置为x86（如果允许的话）
4.下载SDK源代码，自行编译为对应目标平台

PS：旧版本sdk可能会存在一些不完善的地方，建议及早升级到最新版本

**Comment by Tinkerc** [comment]
@fengyhack 确实是编译的问题，我当时是自己重新编译了
