### ISSUE TITLE
将1个BUCKET里的视频转码后保存到另1个BUCKET的方法，SDK里有提供么？

### ISSUE THREAD

**Issue by nextuntil** [qiniu/csharp-sdk#115]
视频是已有的视频。

**Comment by fengyhack** [comment]
@nextuntil 

你所说的“视频是已有的视频”指的应该是已保存在空间中的视频吧？

目前在portal（开发者平台）页面有相应的功能（“音视频转码”），可以将空间中的视频进行转码并保存，为了加快速度，建议使用“私有队列”。

而SDK中提供的是上传后触发数据处理（参见SDK文档和代码示例），因此可以在上传策略中设置转码后保存，当您下次上传视频的时候就可以按照这个方法来做。
