### ISSUE TITLE
Environment.SpecialFolder.UserProfile 在 windows server2008 R2 Standard下获取到是空的

### ISSUE THREAD

**Issue by Tinkerc** [qiniu/csharp-sdk#116]
UploadManager.cs 文件里面 分片上传的时候因获取目录为空导致报错

原
string home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
改成如下就好了
string home = Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData);

**Comment by fengyhack** [comment]
@Tinkerc 
非常感谢，接下来会更新。
