### ISSUE TITLE
目前的7.0.0.5版还是放到Nuget上更新下呗

### ISSUE THREAD

**Issue by xbuilder** [qiniu/csharp-sdk#117]
虽然隔壁7.1已经在开发中了，发布下7.0.0.5也不会耽误多少时间

**Comment by fengyhack** [comment]
@xbuilder 

已更新至NuGet `Qiniu.paf` 7.0.6

```
Install-Package Qiniu.paf
```

请注意，此版本存在一个已知的细节问题。

**Comment by xbuilder** [comment]
@fengyhack 
已知问题是说，传大文件后内存没有释放的问题？

**Comment by fengyhack** [comment]
@xbuilder 
是的
