### ISSUE TITLE
linux下上传图片到七牛云的时候报错如下。

### ISSUE THREAD

**Issue by kencery** [qiniu/csharp-sdk#123]
1.C#写的程序在windows下没有任何问题可以上传到七牛云，但是将项目部署到linux下则上传出现如下错误？大家有遇到过的没有呢？
![image](https://cloud.githubusercontent.com/assets/7973271/21921001/e2b7d36c-d99f-11e6-886e-b50476658e53.png)
2.上传代码图下所示：
![image](https://cloud.githubusercontent.com/assets/7973271/21921064/62f32bda-d9a0-11e6-85c5-225e4c84a7e7.png)

**Comment by fengyhack** [comment]
@kencery  感谢反馈。
可能是CRLF的问题。后续这边做一下测试，如果是这个问题的话会尽快更新

**Comment by kencery** [comment]
@fengyhack   恩恩，默默地等待中，希望能快点搞好么~~~~

**Comment by fengyhack** [comment]
@kencery 
确实是CRLF的问题。
目前该问题已修复，参见[v7.2.5 for .NET Core](https://github.com/qiniu/csharp-sdk/releases/tag/v7.2.5)
后面会推送至NuGet

**Comment by kencery** [comment]
@fengyhack  厉害，解决问题的速度很快呀，当推送到NuGet上的时候，通知一下哈~~~~~

**Comment by fengyhack** [comment]
@kencery 已发布，欢迎使用。

**Comment by kencery** [comment]
@fengyhack  现在这个源码和.net core源码的版本号是否一致了呀？我这个错误是在.net core下遇到的，所以我需要修改.net core的Qiniu版本~~~~

**Comment by fengyhack** [comment]
@kencery 

直接安装就可以了，版本号是一致的，最新版本7.2.5，其中.NET Core基于netstandard1.6
```
Install-Package Qiniu.Shared
```

如果有错误，可以贴上来看看
