### ISSUE TITLE
上传有无支持HTTPS打算

### ISSUE THREAD

**Issue by MengYunfan** [qiniu/csharp-sdk#124]
从目前的的代码来看，虽然服务器返回了上传的https接口，但是sdk中限制了，请问近期可有支持https上传的打算

**Comment by MengYunfan** [comment]
另外从服务器返回的数据来看，https上传似乎不支持cdn加速（不知道是不是合并了）

**Comment by fengyhack** [comment]
@MengYunfan 感谢您的反馈。
事实上7.2版本SDK已经有对于HTTPS的支持了。
如需启用HTTPS，请在Qiniu.Common.Config中设置，另参见[使用指南](http://oiy037d6a.bkt.clouddn.com/csharp-sdk-man-v7.2.4/index.html)中的"注意事项"

**Comment by MengYunfan** [comment]
抱歉，因为我之前看到的是v7.0.0.5版本，，，
