### ISSUE TITLE
代码写完后运行过没有？？？？

### ISSUE THREAD

**Issue by rocgao** [qiniu/csharp-sdk#126]
你们的代码写完后运行过没有？SimpleUploader.uploadStream方法里构建报文格式都不正确，一调用就返回400错误。另外PutPolicy里Deadline是可以set的，但又同时提供了setExpires，你们打算让开发者怎么用？
建议你们写c#的时候用心一点，起码得使用c#的命名规范。

**Comment by fengyhack** [comment]
1.是否有打印详细报错信息，如果有，请贴出来以便分析。

2.返回400错误的一个可能原因是Zone设置不正确（因为没有提供可参考的报错信息，所以暂不确定）。请参考[使用指南-v7.2.5](http://oiy037d6a.bkt.clouddn.com/csharp-sdk-man-v7.2.5/index.html)中的**注意事项**，其中有关于Zone的设置。

3.关于PutPolicy里的Dealine（unix时间戳），它是可以直接设置的，或者使用setExpires来设置。相对来说后者更为方便，比如setExpires(3600)表示设置为1小时后过期，它会自动计算出对应deadline值。两种设置方式最终效果是一样的，选择其中一种方式即可。

4.关于命名规范，确实会有让人不习惯的地方。不过考虑到不同语言版本SDK的统一，会有一些折中，这些命名风格参考了java-sdk

5.每次更新后的SDK都有对应版本的参考文档以及使用指南（在项目的README页面以及官网文档上都能找到），参考这些文档将有助于你理解和使用此SDK。
