### ISSUE TITLE
单元测试 怎么没有了？

### ISSUE THREAD

**Issue by MengYunfan** [qiniu/csharp-sdk#129]
因为我在做 [Qiniu.uwp](https://github.com/MengYunfan/Qiniu.uwp)，从7.2.x版本开始改用了HttpClient很好，但是为啥单元测试没有了，是还没来得及写吗？

没有单元测试改起来很不方便啊！

**Comment by MengYunfan** [comment]
另外从代码中看到httpclient并未设置禁止重定向（WebRequest版本也没有设置禁止重定向，不知道新版本删掉了是出于何种考虑），

**Comment by MengYunfan** [comment]
最后还想问下可有支持uwp的打算？

**Comment by fengyhack** [comment]
@MengYunfan 
感谢您的反馈。
新版本(7.2+)确实还有一些地方不够完善，测试也很难做到详尽。
测试的话暂时用的是MSVS自带的测试工具，后续会考虑加入unit test
另外，UWP支持已列入计划，如果您有好的方案可以提交过来帮助改进。

**Comment by MengYunfan** [comment]
嗯，如果可以支持uwp的话，那我就不用再改了。
要支持uwp的话，文件上传部分和加密部分可能要稍微改一下
就目前而言，比较关心的是文件上传部分的代码最好可以改成Uwp中的StorageFile，还有建议把函数名改一下，[dev](https://github.com/MengYunfan/Qiniu.uwp/tree/dev)分支已经改完了，这是一点小建议，可以看一下
