### ISSUE TITLE
7.2.6 的UploadManager内的uploadStream方法怎么被删掉了

### ISSUE THREAD

**Issue by xbuilder** [qiniu/csharp-sdk#133]
如题

**Comment by fengyhack** [comment]
UploadManager以PUT_THRESHOLD作为阈值（可手动设置），然后根据待上传文件或数据的长度来选择FormUploader或者ResumableUploader。
对于Stream来说，它的长度**可能是不确定的**，因此并未实现在UploadManagerer中。
不过请放心，你仍然可以使用FormUploader或者ResumableUploader来上传一个Stream。

**Comment by xbuilder** [comment]
@fengyhack 
读取本地文件的 FileStream、接收客户端 Form 提交的 InputStream 情况下，Stream的长度是确定的。
我猜你说的长度不确定情况可能是指认为的往Stream里Write数据。如果是这样的逻辑，那么无论是 FormUploader 还是 ResumableUploader 在上传过程中也会出问题。

我现在这边的环境是这样的。老项目使用了一套内部的文件系统，这套东西运维成本太高，准备把这块迁移到第三方云存储，综合考虑，这些老项目不打算对客户端的文件上传进行改造（不使用 uploadToken 直传）。

所以说改造方案是客户端的上传传到内部的文件服务器，通过内部文件服务器转存到第三方云存储。那么在这个过程中，基于 Stream 的上传方式就格外重要了，因为另外两种方式要么就是要把客户端上传的文件先保存到文件服务器本地，再进行读取上传到云存储；要么就是要把文件先读取到内存中再上传到云存储（文件大部分会是一些 3D 模型，体积大）。只有用Stream的方式转发最合适（针对7.2.4版本已经测试过，行得通）。

PS：如果实在纠结长度问题，可以在 uploadStream 方法提供可选参数 fileLength，若传入则以传入参数为准，未传入则以Stream的长度为准。

**Comment by fengyhack** [comment]
@xbuilder 
感谢你的认真回复，基本同意你的看法。

UploadStream功能确实是有必要的，对于类似FileStream这种可计算Stream.Length的，后续更新版本会放在UploadManager中。

事实上，对于所谓“流长度不确定”的情形，SDK中的处理办法也并不完美，目前的做法是循环读取直至遇到“流末尾”（actual=0）：
```
int actual = Stream.Read(byte[] buffer, int offset, int count)
```
