### ISSUE TITLE
增加批量对文件的生命周期进行更新的功能

### ISSUE THREAD

**Issue by jacksonwj** [qiniu/csharp-sdk#134]
当前更新文件生命周期的方法如下：
```
updateLifecycle(bucket, key, deleteAfterDays)
```
如果想批量更新多个文件的生命周期，只能在循环中去调用该方法（因为担心服务器响应的问题，还得采用 Thread.Sleep、异步多线程或 Parallel 并行的方式），这样做其实不太科学，本来一般来说，Update 操作都支持单个或多个的。

所以，建议是否可以考虑增加批量更新的功能？
> 比如：允许第二个参数是泛型列表 List&lt;string&gt;、数组 string[]、或者用特殊符号分隔多个 key 的字符串、……等方式。

PS. [我是从 segmentfault 过来的](https://segmentfault.com/q/1010000008180123)

**Comment by jemygraw** [comment]
可以使用Batch接口操作
