### ISSUE TITLE
建议开放 JSON 解析器

### ISSUE THREAD

**Issue by jacksonwj** [qiniu/csharp-sdk#135]
在七牛官方的 SDK 中的 JSON 解析上，选用了 Json.NET。

个人建议：**将 JSON 的解析器开放出来，让开发者自行选择。**

> 性能比 Json.NET 好的有几个，什么 [Jil](https://github.com/kevin-montrose/Jil)、[ServiceStack.Text](https://servicestack.net/text)、……
甚至，不用 JSON 格式，直接用 Google 的 ProtoBuf（[官方版本](https://developers.google.cn/protocol-buffers)、[C# 版本](https://github.com/mgravell/protobuf-net)）或 Apache（Facebook）的 [Thrift](http://thrift.apache.org/) 进行，也可以。
因为毕竟这里只是一个传参，性能越快越好。

如果一定要用 JSON，建议把解析器开放出来。这样，在我们的项目中，不用单单为了使用七牛的 SDK 而去添加 Json.NET 的引用。

**Comment by fengyhack** [comment]
[v7.2-ext-json](https://github.com/fengyhack/csharp-sdk/tree/v7.2-ext-json)此版本完全开放JSON解析器并移除Json.NET依赖，供您参考。
