### ISSUE TITLE
无法上传文件

### ISSUE THREAD

**Issue by MengYunfan** [qiniu/csharp-sdk#139]
Hi：
7.2.x版本中使用FormUploader.UploadFileAsync()上传文件失败，错误信息：{"error":"file is not specified in multipart"}
但是FormUploader.UploadDataAsync()方法没有问题，望尽快修复。代码[请见](https://github.com/MengYunfan/Qiniu.uwp/blob/dev/Qiniu.SampleApp/MainPage.xaml.cs)

还是之前的那个issue中提到的，希望尽快添加单元测试

另外很高兴看到了7.2.7添加了对uwp支持（我终于不用改了），但是还是有个小小的建议，能否把函数名改一改，已经改了一大部分了，加油！！！

**Comment by fengyhack** [comment]
@MengYunfan 
感谢反馈。也特别感谢您对于UWP这块做的贡献。

1.使用的SDK是否7.2.7版本？这里测试并未出现问题，如果再次出现该问题，请反馈一下，这边也会继续排查。

2.单元测试后续会添加(可能是xUnit，待定)

3.需要改动的地方您可以帮忙指出来，我们会仔细考察（后续更新或改动会更加慎重）。

**Comment by MengYunfan** [comment]
Hi,
对的是7.2.7版本其实7.2.6也有这个问题，已经确认了有问题，使用的是你发布的sdk（顺便提示下uwp版本的project.json丢了，下次麻烦补上吧！）

**Comment by MengYunfan** [comment]
因为7.2.6版本的时候发现了这个问题，但是7.2.6那会刚好是过年，所以打算等到年后再说，今天看到了新版，但是很遗憾这个问题依然存在，另外想对你说一声辛苦啦！

**Comment by MengYunfan** [comment]
因为我可能有一点点强迫症，所以还是希望如果可以的话请把函数的名称全部改成首字母大写（私有函数看不到，其实也可以不改）

**Comment by fengyhack** [comment]
已更新至版本v7.2.8并修复此问题：{"error":"file is not specified in multipart"}

**Comment by MengYunfan** [comment]
Hi：
新版本UploadFileAsync确实没有问题了，看了下[issue140](https://github.com/qiniu/csharp-sdk/issues/140)原来是中文路径的问题

所以顺便测试了一下UploadDataAsync发现如果saveKey为中文也会出现问题

**Comment by fengyhack** [comment]
@MengYunfan 
感谢您的反馈，我们检查一下代码，尽快修复。

**Comment by MengYunfan** [comment]
@fengyhack 
很高兴看到7.2.9版本中加入了单元测试，但是非常遗憾的是NUnit Adapter 3.x版本不支持uwp，所以希望可以同时维护一个MS Test的uwp版本，比如 [Qiniu.uwp](https://github.com/MengYunfan/Qiniu.uwp/tree/dev/Qiniu.UnitTests)

另外在测试过程中发现了两个问题：
![qq 20170216144816](https://cloud.githubusercontent.com/assets/8027453/23010814/5b59949a-f458-11e6-8ef5-619628a58340.png)

第一个问题是计算时间戳防盗链的时候UrlHelper中如果原始url中不包含“?” index就变成了-1
![qq 20170216150043](https://cloud.githubusercontent.com/assets/8027453/23010881/b4c9bb54-f458-11e6-9521-80fb62b45c22.png)


第二个问题是在使用ResumableUploader.UploadDataAsync()上传一个13MB左右的文件时，出现了问题，代码就在上面的连接中，希望可以解决一下这个问题


另外现在的单元测试的覆盖率是不是有点低，希望可以覆盖所有

**Comment by fengyhack** [comment]
@MengYunfan 感谢您详细的反馈。
1.UnitTest方面，后面会新增一个MSTest版本，并且增加覆盖率，尽量做到完全覆盖
2.UrlSplit这个函数存在缺陷，需要修改
3.ResumableUploader.UploadDataAsync()这个函数我们会重新审查一下代码，尽快修复

**Comment by fengyhack** [comment]
单元测试方面还要继续完善，请关注后续更新。
