### ISSUE TITLE
7.2.8 版本 UploadStream 有问题

### ISSUE THREAD

**Issue by xbuilder** [qiniu/csharp-sdk#143]
![image](https://cloud.githubusercontent.com/assets/10357081/22818395/fbd354a2-efa7-11e6-80c5-8888422f9f2c.png)
如图，7.2.4是可以上传成功的

**Comment by fengyhack** [comment]
感谢反馈，我们会检查一下SDK，尽快修复。

**Comment by xbuilder** [comment]
我去测试一下7.2.9 :)

**Comment by fengyhack** [comment]
@xbuilder 
感谢反馈。
初步判断你的运行环境在.NET Framework 4.5+,上传时使用的更可能是FormUploader.UploadStream
但是从RefText内容（HTTP发送multipart数据出错）来看，还不能给出最终结论，所以需要更多的信息

如果可以，请提供尽可能多的信息，比如：
1.使用SDK的环境，比如Win10 x64, .NET 4.5.2, WinForm/WPF/ASP.NET等等
2.使用的具体函数和参数，比如FormUploader.UploadStream(WHAT_Stream,...)或它的async版本
3.上传目标空间所在区域，可参阅[使用指南](http://oiy037d6a.bkt.clouddn.com/csharp-sdk-man-v7.2.11/index.html)中的"注意事项"部分
4.如果都没有问题，可以先测试一下其他功能，比如UploadFile或者UploadData等 
5.如果可以，请提供扼要的抓包信息(适用于Windows的抓包工具有Charles,Fiddler,WireShark等)

**Comment by xbuilder** [comment]
@fengyhack 
莫名其妙的好了。。没搞明白@_@

**Comment by fengyhack** [comment]
@xbuilder 感谢反馈。
这个问题暂且认为是"HTTP POST出错"(参考result.RefText的内容)。

这里再提一下有关UploadStream的使用吧。

UploadStream函数的第一个参数Stream，这个流应该是可读的，并且能够顺利读取到末尾（SDK中以“Stream.Read返回0”作为“流已达末尾”的依据），比如FileStream和HttpResponseStream等。

使用`UploadManager`的UploadStream要求Stream支持查找（或者说可以获取/确定Stream.Length）;
而`FormUploader`或者`ResumableUploader`的UploadStream则无此要求。

顺便贴一个例子，它示意了如何上传NetStream(来自网络回复的数据)到空间：
```csharp
string token = "<UPLOAD-TOKEN>";
string url = "http://<SOME-URL>/001.jpg";
var wReq = System.Net.WebRequest.Create(url) as System.Net.HttpWebRequest;
var resp = wReq.GetResponse() as System.Net.HttpWebResponse;
using (var stream = resp.GetResponseStream())
{
    // 请不要使用UploadManager的UploadStream方法，因为此流不支持查找
    // 请使用FormUploader或者ResumableUploader的UploadStream方法
    FormUploader fu = new FormUploader();
    var result = fu.UploadStream(stream, "001.jpg", token);
    System.Console.WriteLine(result);
}
```
当然，这个示例也可以在源代码的examples文件夹下找到。

**Comment by xbuilder** [comment]
@fengyhack 
感谢提供 NetStream 的示例代码，这部分感觉在 `UploadManager` 可以提供 `UploadFromNet(url,uploadType)` 和  `UploadFromNet(netStream,uploadType)`，由调用者自己来决定用什么方式上传

PS：本主题这个上传错误貌似是因为我所在的网络环境造成的，尴尬了（开发环境上传失败，生产环境没问题）。

**Comment by fengyhack** [comment]
@xbuilder 
感谢反馈。目前暂认为这个问题是客观导致的，并非SDK缺陷。
