### ISSUE TITLE
私有空间下载失败

### ISSUE THREAD

**Issue by superlbr** [qiniu/csharp-sdk#152]
环境：win10 .net v4.0 编译,运行在08R2上
版本：git clone代码，新鲜编译出来的
错误：生成的下载链接报错{"error":"download token auth failed"} 
详细：签名出来的链接如下 http://img.cnhsjz.com/54596E4D2218.zip?e=1487917419&token=xxxxxxxxxx:URQMxUrMu_ykqUbLjxKH35-xqeA=
生成代码：如下图
![image](https://cloud.githubusercontent.com/assets/8142164/23291593/91e8febe-fa94-11e6-8325-6dcd8b9d4e05.png)

提过工单，但是人家签名出来就可以，附上可用的url
   http://xxx.cnhsjz.com/54596E4D2218.zip?e=1582519015&token=xxxxxxxxxxx:CCPWWXPKBA5Zv8JqsiQJpVpYugc=

**Comment by superlbr** [comment]
还有就是csharp-sdk/src/Qiniu/Util/StringHelper.cs下面：
![image](https://cloud.githubusercontent.com/assets/8142164/23291796/e9877b72-fa95-11e6-89f3-a628af00639a.png)

这是。。。。

**Comment by superlbr** [comment]
经nodejs版本对比，已发现源码问题若干，还是自己写吧

**Comment by superlbr** [comment]
我觉得作者还是留意下吧，这个签名完全是错的

**Comment by fengyhack** [comment]
@superlbr 
感谢反馈。
这个问题是SDK源代码里面的错误，基准应该是1970.1.1.00，但是代码里面错写成了1910.1.1.00
这边会尽快修复。

**Comment by superlbr** [comment]
@fengyhack除去这个，下载凭证不对。。。帮忙看下，谢谢

**Comment by fengyhack** [comment]
@superlbr 
目前此问题，请升级至最新版本(v7.2.12)然后进行测试。

**Comment by superlbr** [comment]
下载凭证还是不对，我又测了一次

**Comment by fengyhack** [comment]
请确认一下使用的是否最新的7.2.12版本SDK

**Comment by superlbr** [comment]
确定，我手动编译了一下不行，然后再用nuget装，一样不可以

**Comment by ShawnHill233** [comment]
我今天遇到过这种情况，卡了半天。JS SDK中使用downtoken_url参数时，JS会上传domain和key，查看一下你的domain的格式，正确的是“http://xx.bkt.clouddn.com”，而不是“http://xx.bkt.clouddn.com/”，最后不能有斜杠。
