### ISSUE TITLE
CDN Manager无法刷新文件

### ISSUE THREAD

**Issue by MengYunfan** [qiniu/csharp-sdk#155]
这个是CDNManager的方法
![qq 20170228134755](https://cloud.githubusercontent.com/assets/8027453/23393292/d5e0883c-fdbc-11e6-84ea-cafdbc8f611f.png)
创建刷新请求
![qq 20170228134806](https://cloud.githubusercontent.com/assets/8027453/23393297/db69a3f6-fdbc-11e6-9fa5-a54d95939400.png)
但是问题的关键在于
![qq 20170228135145](https://cloud.githubusercontent.com/assets/8027453/23393329/0ddb7620-fdbd-11e6-88ab-afde2ce4854c.png)
 直接就会抛出异常了

**Comment by MengYunfan** [comment]
这个问题一直存在，所以还请尽早把单元测试补完

**Comment by fengyhack** [comment]
@MengYunfan 
感谢反馈。
单元测试实际上覆盖到这个刷新函数，但是测试用例就一个。
这两个参数没有做检查(比如设置为null)，后续更新一下SDK代码修复它。
