### ISSUE TITLE
ResumableUploader JsonReadException

### ISSUE THREAD

**Issue by 742435081** [qiniu/csharp-sdk#162]
![default](https://cloud.githubusercontent.com/assets/14551816/24333353/cdc214fa-1288-11e7-8fe0-194e8b5fd8d3.png)

**Comment by fengyhack** [comment]
@742435081 
感谢反馈。

从代码来看，使用的是[这个函数](http://oiy037d6a.bkt.clouddn.com/csharp-sdk-ref-v7.2.15/html/M_Qiniu_IO_ResumableUploader_UploadFile_7.htm)
其中的file.Path+".resume"是断点记录文件，这个文件内容是JSON文本。

从错误消息提示来看，是记录文件中JSON解析错误(比如遇到错误字符)，如果检查此文件内容，或者方便的话贴上来以便我们排查问题。

或者，删除此文件重试一次(这样的话，会从头开始上传)。

**Comment by 742435081** [comment]
不是SDK问题，不知为什么路由经常屏蔽。估计因为突发流量，返回了一个html文件。
