### ISSUE TITLE
Uri.EscapeDataString 方法 (String)不支持长URL

### ISSUE THREAD

**Issue by bernieyangmh** [qiniu/csharp-sdk#163]
Uri.EscapeDataString方法
https://msdn.microsoft.com/zh-cn/library/system.uri.escapedatastring(v=vs.110).aspx
具体demo链接
https://github.com/qiniu/csharp-sdk/blob/bea3132a83351ad40bd6db355b8885a68152f0b6/src/Qiniu/Util/StringHelper.cs

![image](https://cloud.githubusercontent.com/assets/18359013/24793413/82fe1056-1bb4-11e7-9568-3ed10059462e.png)
在客户进行多文件压缩的时候，客户选择了1000个文件上传
会报无效的url：url字符串太长

**Comment by fengyhack** [comment]
感谢反馈。
从问题描述来看，应该是fops太长导致`Uri.EscapeDataString`方法出错。
后续版本会修复此问题。
