### ISSUE TITLE
提交一个错误和一个建议

### ISSUE THREAD

**Issue by hjkl950217** [qiniu/csharp-sdk#166]
错误:VS中用Nuget获取到的是7.0.0版,且命名空间和项目中的7.2相差很大,建议在Nuget中更新一一上
建议:不管是项目中最新的 还是从VS中获取到的,都没有注释,虽然有网页版的注释,但是没有在代码中调用时就能看到的舒服呀,查看网页版的文档毕竟慢点,建议改进一下,添加注释的xml文件

**Comment by jemygraw** [comment]
谢谢
