### ISSUE TITLE
Why you removed all examples in master branch?

### ISSUE THREAD

**Issue by alexinea** [qiniu/csharp-sdk#177]
Why you removed all examples in master branch? I just saw them several days ago.

**Comment by jemygraw** [comment]
please view examples under https://github.com/qiniu/csharp-sdk/tree/master/src/QiniuTests

**Comment by alexinea** [comment]
@jemygraw Thank you. And another question, when can we get Qiniu.Shared ver. 7.3.0 on nuget.org? I found a lot of breaking changes from ver. 7.2.15 to ver. 7.3.0. It looks hard to smooth upgrade to the new version.

**Comment by jemygraw** [comment]
i am working on it, will be online in few days.

**Comment by alexinea** [comment]
Copy that :)  Thx a lot @jemygraw .

**Comment by jemygraw** [comment]
nuget is ok. 7.3.0 @alexinea

**Comment by alexinea** [comment]
@jemygraw  nuget is not ok.

**Comment by jemygraw** [comment]
@alexinea any errors?

**Comment by alexinea** [comment]
@jemygraw SDK 7.2.x is still able to run on NETStandard2.0, while SDK 7.3.x can only run on Nfx? We all know that Nfx cannot be used on Linux...
