### ISSUE TITLE
关于FormUploader类里的UploadFile方法传递自定义参数问题

### ISSUE THREAD

**Issue by dongzhaosheng73** [qiniu/csharp-sdk#178]
调用qiniu云SDK 附带的自定义参数在返回的结果中并没有拿到 请问这是BUG还是调用方式不对？已参照文档的方式调用文件上传成功自定义参数没有拿到，希望作者帮助解决下这个问题谢谢。 

`var extra = new System.Collections.Generic.Dictionary<string, string>();
            extra.Add("Test", "TestData");`

`var uploadResult =  qiniuUploader.UploadFile(
                clientUploader.SourcePath,
                clientUploader.SaveKey,
                token,
                extra);`

**Comment by jemygraw** [comment]
额外的参数名称必须以 x: 开头，也就是应该是 extra.Add("x:Test","TestData")这样才可以，另外指定的可选参数值必须不能为空。
