### ISSUE TITLE
上传照片时如何通过自定义参数中填入魔法参数拿到魔法变量值的回调结果？

### ISSUE THREAD

**Issue by dongzhaosheng73** [qiniu/csharp-sdk#180]
` cfg.ExtraParameters.Add("x:Ave", "$(imageAve)");`
` cfg.ExtraParameters.Add("x:Width", "$(imageInfo.width)");`
`cfg.ExtraParameters.Add("x:Height", "$(imageInfo.height)");`
`cfg.ExtraParameters.Add("x:Size", "$(fsize)");`
客户端回调给服务器可以通过CallbackBody 那么客户端本身如何拿到魔法变量的结果？是否可以通过ExtraParameters提交魔法参数拿到结果？

**Comment by dongzhaosheng73** [comment]
通过returnbody 传递魔法参数拿回结果 不能与callback一起用

**Comment by jemygraw** [comment]
没懂具体说的意思，不过上面的扩展参数里面是无法使用魔法变量的，因为扩展参数代表的含义是客户端额外提交上来的参数
