### ISSUE TITLE
7.3.0 版本能否在 Nuget 上传一下？

### ISSUE THREAD

**Issue by fudiwei** [qiniu/csharp-sdk#181]
Release 五天前已经有了 7.3.0，但 Nuget 上的包依然是 7.2.15 的，能否更新一下？

**Comment by liangchaoboy** [comment]
![image](https://user-images.githubusercontent.com/17689793/30682336-e4e32f40-9edb-11e7-85ed-a31f02ce95dc.png)

已更新，刷新下 nuget

**Comment by liangchaoboy** [comment]
https://www.nuget.org/packages/Qiniu/

**Comment by fudiwei** [comment]
@liangchaoboy Qiniu 这个源似乎只支持 .NET Framework 吧？我的项目使用的是 .NET Standard，所以用的 Qiniu.Shared 这个源，还没有更新。

**Comment by fudiwei** [comment]
emmmm... 两个包似乎不是一个所有者，一个是 qiniusdk，一个是 fengyhack。后者是第三方源还是贵司的工作人员呢？

**Comment by jemygraw** [comment]
用 qiniusdk 这个官方的。目前官方只计划支持 .NET Framework。如果你希望支持.NET Core,那么可以使用 后者。

**Comment by fudiwei** [comment]
曾经的 7.2.9 版本在源码中提供了 .NET Standard 的项目，是什么原因导致了在 7.3.0 中移除了对 .NET Standard 的支持呢？

后续是否会支持 .NET Standard（.NET Frameword/.NET Core 类型的项目都只能在各自项目类型中引用，.NET Standard 才是同时可以被两者都引用）呢？

如果官方没有计划的话，是否接受来自社区的 PR？毕竟还是希望有一个 NuGet 源可以用而非直接编译源码。

**Comment by jemygraw** [comment]
如果需要可以使用之前的支持的版本。
