### ISSUE TITLE
.Net Core2.0 都发布好几个月了，希望能尽快支持 Standard和 Core

### ISSUE THREAD

**Issue by aehyok** [qiniu/csharp-sdk#182]
.Net Core2.0 都发布好几个月了，希望能尽快支持 Standard和 Core

**Comment by cuibty** [comment]
希望能尽快支持 .NET Standard 2.0

**Comment by alexinea** [comment]
本来还能在ns20内引用的，现在7.3又不行了，几个意思？

**Comment by jemygraw** [comment]
有个第三方版本，未测试，可以看看https://www.nuget.org/packages/Qiniu.NetCore/

**Comment by alexinea** [comment]
😢 我们最终自己实现了……

**Comment by cuibty** [comment]
@alexinea 大兄弟不简单啊！

**Comment by Gary-Ge** [comment]
@alexinea 大兄弟实现的时候要改的多不多
