### ISSUE TITLE
QueryZone Error:  code: -256, text: , ref-text: 

### ISSUE THREAD

**Issue by haobingwang** [qiniu/csharp-sdk#183]
【异常类型】：Exception
【异常信息】：QueryZone Error:  code: -256, text: , ref-text: 
【堆栈调用】：   在 Qiniu.Common.ZoneHelper.QueryZone(String accessKey, String bucket)

补充信息：
1. 没有绑定域名，使用的是七牛默认生成的域名。
2. 业务场景：发生在上传图片时，集中在10秒内，30 个客户端同时进行上传5M大小的图片。

**Comment by jemygraw** [comment]
这个一般是网络情况不好，解析失败之类的。

**Comment by haobingwang** [comment]
😢 有什么好的解决方案或建议么？ @jemygraw

**Comment by jemygraw** [comment]
测试下网络，如果网络有问题，修复下就好了。

**Comment by iamvoxer** [comment]
补充一个原因，mac电脑访问七牛报这个错误，原因是mac电脑断电了，系统时间不知道什么原因自动恢复到2018年1月1号，导致error -256失败
