### ISSUE TITLE
qiniu SDK访问吞度量有多大？

### ISSUE THREAD

**Issue by harlanc** [qiniu/csharp-sdk#187]
正在使用的qiniu的图床功能(免费的)，并且使用qiniu SDK 把上传图片功能集成到了一个开源的截图工具中,这个截图工具的用户量官方说超过一个亿。如果release这个功能，他们担心用户量过大qiniu的server会垮掉。所以想知道七牛的吞吐量有多大？另外想知道是不是各个国家是不是都能使用七牛的图床服务？还是只有中国才能用？

**Comment by jemygraw** [comment]
这个是服务端的吞吐量吧，如果访问带宽在1TB以下的，随便用吧。
