### ISSUE TITLE
7.2.15支持.Net Standard 2.0，到了7.3又不支持了

### ISSUE THREAD

**Issue by Gary-Ge** [qiniu/csharp-sdk#189]
7.3的SDK核心代码重写了，还没有完全兼容.Net Standard 2.0 ？
希望尽快加入支持~

**Comment by jemygraw** [comment]
未来不打算支持，如果需要，可以看第三方的 https://www.nuget.org/packages/Qiniu.NetCore/ 未测试，可以自行测试看看
