### ISSUE TITLE
Json.net 序列化出错 

### ISSUE THREAD

**Issue by NMSAzulX** [qiniu/csharp-sdk#190]
.NET版本：4.6
Json版本：11.0.2
Qiniu版本：7.3.1.1

[FormUpload] Error: 未能加载文件或程序集“Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

**Comment by NMSAzulX** [comment]
七牛依赖项：Newtonsoft.Json (>= 10.0.3)

**Comment by jemygraw** [comment]
JSON的依赖看看是不是对应.NET版本的那个版本。
