### ISSUE TITLE
mkzip 操作支持传入 alias 参数

### ISSUE THREAD

**Issue by ipy** [qiniu/csharp-sdk#66]
多文件压缩方法 `Qiniu.PFOP.Mkzip.doMkzip` 目前不支持传入 alias:
https://github.com/qiniu/csharp-sdk/blob/develop/Qiniu/PFOP/Mkzip.cs#L30
这个方法可以接收一个 alias 数组，或是把 urls 换成 Dictionary.
目前想到两个方式：
1. 接收一个 alias 数组
   
   ```
   public String doMkzip(String bucket, String existKey, String newFileName, String[] urls, string pipeline, String[] aliases = null)
   ```
2. urls 类型改成 Dictionary, key 为 url, value 为 alias
   
   ```
   public String doMkzip(String bucket, String existKey, String newFileName, Dictionary<string,string> urls, string pipeline)`
   ```

目前主要使用的场景是文件存储路径包括分级文件夹，压缩时需要把路径展平，所以比较需要别名功能。

**Comment by jiaojunjiahanlin** [comment]
好的，这个我们来修复下。扩展下别名的功能。
