### ISSUE TITLE
分片上传为什么没有将 block 分为 多个 chunk 进行上传？

### ISSUE THREAD

**Issue by wujun4code** [qiniu/csharp-sdk#67]
代码里面没有解释如何对一个 block 进行多个 chunk 进行分片上传的步骤，这个对一些网络不好以及移动端的复杂网络情况 分 chunk 进行上传是很重要的，请问这部分代码有计划提供么？

**Comment by longbai** [comment]
正在编写这部分的代码。

**Comment by freewing99** [comment]
我已经实现了……我是基于[Task-based Asynchronous Pattern (TAP)](https://msdn.microsoft.com/en-us/library/hh873175(v=vs.110).aspx)实现了一版，另外我建议把源代码里面所有C相关的命名格式换成C#风格的吧……

**Comment by longbai** [comment]
@freewing99 :+1:  android, objc 都实现了这种异步方式上传，同事正在写，您更快 :)

**Comment by cuibty** [comment]
真心建议把代码风格换成C#的，各种C和C#代码用，我也是醉了。
