### ISSUE TITLE
Newtonsoft.JSON 被强制覆盖

### ISSUE THREAD

**Issue by JeffreySu** [qiniu/csharp-sdk#84]
Nuget上面的package，直接包含了一个Newtonsoft.JSON.dll，导致已经通过Nuget安装了Newtonsoft.JSON的引用会被覆盖（降级），产生版本冲突。第三方的dll只需要依赖就会自动安装的。

**Comment by JeffreySu** [comment]
如果程序里面已经有其他版本的Newtonsoft.JSON，貌似也会有问题，提示“未能加载文件或程序集“Qiniu.4.0”或它的某一个依赖项。试图加载格式不正确的程序。”

**Comment by longbai** [comment]
收到，我们看下

**Comment by xaclincoln** [comment]
我遇到同样的问题，项目中已经添加了6.0.4版本的Newtonsoft.Json，但是安装Qiniu包后，会下载6.0.1版本的Newtonsoft.Json，按道理Newtonsoft.Json支持SemVer，应该不需要额外安装更低版本。

**Comment by chiaki-yu** [comment]
相同的问题  我用的8.0.2  结果强制给我换成了6.0版本   我的系统运行报错，换回8.0  sdk报错

**Comment by HADB** [comment]
@JeffreySu 这个问题我两年前就跟他们说过好几次了，还是这样！ #61

**Comment by xaclincoln** [comment]
我前段时间大概看了下代码，原因在于qiniu的csharp-sdk中引用的Newtonsoft.Json.dll不是由Nuget包定义的，而是直接拷贝了一个大概4.0版本的Dll文件，真是醉了。。。

**Comment by HADB** [comment]
@longbai nuget就如同npm一样重要啊，尤其是像newtonsoft.json这样常见的包更是要用nuget来管理。最近重新在搞一个之前的项目，项目里其他的包都更新了，唯独不敢轻易更新七牛的包。来github一看，幸亏没更新。

**Comment by JeffreySu** [comment]
我们现在七牛的dll只能本地引用文件，已经不敢用nuget装七牛。什么时候官方可以解决一下这个问题呢？
现在用的这个dll还是半年前七牛的技术通过QQ给我的，要如何自动获得最新的更新？

**Comment by cuibty** [comment]
更新的真是慢

**Comment by cuibty** [comment]
在下真是佩服，Newtonsoft.Json直接打包到nuget。覆盖项目中正在使用的Newtonsoft.Json，关键是它还不更新。我也是醉了。

**Comment by JeffreySu** [comment]
关闭了？这问题是解决了吗？

**Comment by fengyhack** [comment]
这个是关于NuGet打包的问题。
之前的做法是：将Newtonsoft.Json.dll也打包到NuGet，在这种情况下，如果项目中已有Newtonsoft.Json.dll，再添加C# SDK会造成冲突(Json.NET版本不一致/覆盖)，可以卸载Newtonsoft.Json包然后重新安装即可；
后面发布到NuGet上不再打包Newtonsoft.Json.dll，改为自动配置安装（如果没有安装的话）。

除了NuGet方式安装，这个repo上会及时更新最新的Release(包含最新版本的编译包)，可以直接dll方式引用。或者可以从源码编译。

**Comment by HADB** [comment]
最近的一个.net项目中发现，这个bug又回来了，Newtonsoft.Json.dll又直接打进包里了，把原先的11.0替换成10.0了
