### ISSUE TITLE
什么时候有.net core版本？

### ISSUE THREAD

**Issue by cipchk** [qiniu/csharp-sdk#96]

**Comment by longbai** [comment]
已经有开发计划

**Comment by cipchk** [comment]
希望快一点，现在都是自撸HTTP请求。

**Comment by yajiya** [comment]
恩，兄弟们加油。

**Comment by imalexi** [comment]
希望可以快一点翻新一个.NETCORE版本

**Comment by yajiya** [comment]
@longbai 请问计划大概是啥样的？beta版的大概发布时间，有没有？

**Comment by fengyhack** [comment]
正在开发中

**Comment by jamesatgithub** [comment]
@longbai @fengyhack 希望 .NET Core 跟PCL (Xamarin SDK)版 一起推出

**Comment by dictbox** [comment]
目前版本好像稍作修改就可以在.net core上跑了，我这边可以正常上传文件。但还是希望官方尽快出专版，要不每次更新，还得再改一遍。

**Comment by fengyhack** [comment]
.NET Core 版本请戳[这里](https://github.com/fengyhack/csharp-sdk-dnc)，欢迎测试&反馈

**Comment by jamesatgithub** [comment]
@fengyhack 是否可以出一个PCL版的SDK (这样可以支持Xamarin)

**Comment by fengyhack** [comment]
@jamesatgithub PCL版本已经在开发中

**Comment by zhw2101024** [comment]
有没有可能一套代码兼容.net core和.net framework？
两个分支用起来不太方便。
据说以后的.net framework都会基于.net core实现了

**Comment by fengyhack** [comment]
确有消息说以后.NET FX会基于.NET Core实现

但目前二者还是有差异的：
![netfx](http://test.fengyh.cn/qiniu/files/netFx.png)

所以，暂时还是麻烦一点，用两个分支
如果找到合适的兼容方案，肯定会及时更新的。

**Comment by CrazyLibra** [comment]
@fengyhack 现在出了吗？看上一条评论，20天已经过去了。

**Comment by fengyhack** [comment]
.NET Core版本已经有了，在dotnet-core分支以及最新的[csharp-sdk-dnc](https://github.com/fengyhack/csharp-sdk-dnc)
