### ISSUE TITLE
DeleteAfterDays参数问题

### ISSUE THREAD

**Issue by coco163** [qiniu/csharp-sdk#98]
1.七牛C#SDK的DeleteAfterDays参数如何使用；

2.put = new PutPolicy(bucket, 3600); put.DeleteAfterDays = 1;

3.我设置了DeleteAfterDays = 1，按我理解通过这个Token上传的文件会在一天后自动删除，然而并没有；

4.我发现加不加DeleteAfterDays这个参数，对于生成的Token并没有什么变化。
使用的是最新的版本 直接从github下载的

**Comment by longbai** [comment]
我们看下

**Comment by fengyhack** [comment]
**请参考我们维护的另一版本C# SDK(以下简称"新版SDK"): [qiniu-csharp-sdk](https://github.com/fengyhack/qiniu-csharp-sdk)**

**Q: 七牛C#SDK的DeleteAfterDays参数如何使用**
A: 新版SDK中，直接赋值即可PutPolicy putPolicy = new PutPolicy() {DeleteAfterDays=1};

**Q: DeleteAfterDays这个参数添加与否，对于生成的Token有什么变化**
A: 新版SDK中，DeleteAfterDays设置的不同导致UploadToken也是不同的(点击图片可以查看原图)：

![PutPolicy](http://test.fengyh.cn/qiniu/files/QiniuTest-PutPolicy.png)

**Q: 设置DeleteAfterDays=1并上传文件后，在空间中1天之后该文件并未被删除**
A: 在新版SDK中Upload请求PutPolicy参数没有任何问题，空间文件过期自动删除。

另，关于UploadToken的详细介绍，参考[这里](http://developer.qiniu.com/article/developer/security/upload-token.html)

**Comment by coco163** [comment]
谢谢～国庆节快乐～
