### ISSUE TITLE
代码能否按照C#编程风格来编写SDK

### ISSUE THREAD

**Issue by cuibty** [qiniu/csharp-sdk#99]
@fengyhack 已经看到了最新版本的SDK，望重构成 C#编程风格 。 O(∩_∩)O谢谢

**Comment by fengyhack** [comment]
好的

**Comment by alex521** [comment]
为什么传Mac的方式都不一样的？  uploadmanager在token那，bucketmanager又直接在构造里。。。

**Comment by fengyhack** [comment]
多谢指出。传参方式确实没有统一，另外代码风格也要调整，后面会尽快更新
